### ISSUE TITLE
navigator is not defined    branch.init("xyz", {}, function(){});

### ISSUE THREAD

**Issue by aggarwal23deepak** [BranchMetrics/web-branch-deep-linking#335]
If there is a bug or error in this repo, please file the issue here. 

If you need assistance integrating a Branch SDK, please email support@branch.io. Thank you.

ReferenceError: navigator is not defined
    at Object.isEnabled (/Users/deepakaggarwal/deepak/branchSdk/node_modules/branch-sdk/dist/build.min.js:23:42)
    at new M (/Users/deepakaggarwal/deepak/branchSdk/node_modules/branch-sdk/dist/build.min.js:18:626)
    at new V (/Users/deepakaggarwal/deepak/branchSdk/node_modules/branch-sdk/dist/build.min.js:63:179)
    at /Users/deepakaggarwal/deepak/branchSdk/node_modules/branch-sdk/dist/build.min.js:82:337
    at Object.<anonymous> (/Users/deepakaggarwal/deepak/branchSdk/node_modules/branch-sdk/dist/build.min.js:82:615)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

**Comment by jsaleigh** [comment]
@aggarwal23deepak thanks for the note on this! Quick question, was the SDK included in a node.js application by chance?

**Comment by aggarwal23deepak** [comment]
yes it was included in a node.js application intentionally.
so if this sdk not for nodejs , so how can I use branch sdk at server side for making deep linking

**Comment by jsaleigh** [comment]
Hi @aggarwal23deepak , that's correct, this is not meant for nodejs.

I believe what you're looking for is here: https://github.com/BranchMetrics/branch-deep-linking-public-api

If that doesn't help, there are lots of great docs here: https://dev.branch.io/

And if that still doesn't help, you can email support@branch.io.  We have an outstanding support team, they are very knowledgable, and can generally answer any questions you have very quickly.
